"""empty message

Revision ID: 233d7f548b7a
Revises: 9d7365d9ac62
Create Date: 2021-04-17 08:38:48.377190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233d7f548b7a'
down_revision = '9d7365d9ac62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Artist_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('Venue_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'shows_Venue.id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint(u'shows_Artist.id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'Venue', ['Venue_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Artist', ['Artist_id'], ['id'])
    op.drop_column('shows', 'Venue.id')
    op.drop_column('shows', 'Artist.id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Artist.id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shows', sa.Column('Venue.id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key(u'shows_Artist.id_fkey', 'shows', 'Artist', ['Artist.id'], ['id'])
    op.create_foreign_key(u'shows_Venue.id_fkey', 'shows', 'Venue', ['Venue.id'], ['id'])
    op.drop_column('shows', 'Venue_id')
    op.drop_column('shows', 'Artist_id')
    # ### end Alembic commands ###
