"""empty message

Revision ID: 47057593df52
Revises: d4eeb20c299f
Create Date: 2021-04-21 12:15:37.978680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47057593df52'
down_revision = 'd4eeb20c299f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
